import { Class } from './class.types';

export const mockClasses: Class[] = [
  {
    id: 'c1',
    name: '1º Ano A',
    room: 'Sala 101',
    shift: 'Matutino',
    academicYear: '2024',
    studentsCount: 2,
    schoolId: '1',
  },
  {
    id: 'c2',
    name: '2º Ano B',
    room: 'Sala 202',
    shift: 'Vespertino',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '1',
  },
  {
    id: 'c3',
    name: '3º Ano C',
    room: 'Sala 303',
    shift: 'Noturno',
    academicYear: '2024',
    studentsCount: 0,
    schoolId: '2',
  },
  {
    id: 'c4',
    name: 'Alfazema 1',
    room: 'Laboratório',
    shift: 'Integral',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '4',
  },
  {
    id: 'c5',
    name: 'Berçário 1',
    room: 'Berçário 1',
    shift: 'Matutino',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '4',
  },
  {
    id: 'c6',
    name: 'Jardim A',
    room: 'Sala 01',
    shift: 'Vespertino',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '5',
  },
  {
    id: 'c7',
    name: '4º Ano X',
    room: 'Sala 05',
    shift: 'Matutino',
    academicYear: '2024',
    studentsCount: 2,
    schoolId: '6',
  },
  {
    id: 'c8',
    name: '5º Ano Y',
    room: 'Sala 06',
    shift: 'Vespertino',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '6',
  },
  {
    id: 'c9',
    name: '6º Ano Z',
    room: 'Auditório',
    shift: 'Noturno',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '6',
  },
  {
    id: 'c10',
    name: 'Infantil 5',
    room: 'Parque',
    shift: 'Matutino',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '7',
  },
  {
    id: 'c11',
    name: '1º Ano B',
    room: 'Sala 102',
    shift: 'Vespertino',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '8',
  },
  {
    id: 'c12',
    name: 'Canteiro 2',
    room: 'Horta',
    shift: 'Integral',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '9',
  },
  {
    id: 'c13',
    name: '7º Ano A',
    room: 'Sala 07',
    shift: 'Matutino',
    academicYear: '2024',
    studentsCount: 2,
    schoolId: '10',
  },
  {
    id: 'c14',
    name: '8º Ano B',
    room: 'Sala 08',
    shift: 'Vespertino',
    academicYear: '2024',
    studentsCount: 1,
    schoolId: '11',
  },
  {
    id: 'c15',
    name: '9º Ano C',
    room: 'Informática',
    shift: 'Noturno',
    academicYear: '2024',
    studentsCount: 0,
    schoolId: '12',
  },
];
